name: Medium Posts
on:
  push:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  youtube:
    name: latests Posts from Medium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "MEDIUM-POSTS-LIST"
          max_post_count: 4
          feed_list: "https://medium.com/samtdomi"
          date_format: "mmm d, yyyy"
          template: '<tr><td><a href="$url"><img width="140px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td>$newline<td><a href="$url">$title</a> ($date)<br/>$description</td></tr>$newline'
          description_max_length: 140
